# Generated by Django 2.1.4 on 2019-01-15 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='report/')),
                ('remarks', models.CharField(max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
                ('teacher_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TeacherClass')),
            ],
            options={
                'verbose_name': 'Report Card',
                'verbose_name_plural': 'Report Cards',
                'ordering': ('-date',),
            },
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TeacherClass'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_days_absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_days_present',
            field=models.IntegerField(default=0),
        ),
    ]
