# Generated by Django 2.1.4 on 2019-01-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190115_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report/'),
        ),
    ]
